apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mp7hpw9nj-nodejs 
  janus-idp.io/tekton: mp7hpw9nj-nodejs
  backstage.io/kubernetes-id: mp7hpw9nj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mp7hpw9nj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml