apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mp7hpw9nj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mp7hpw9nj-nodejs 
  name: mp7hpw9nj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mp7hpw9nj-nodejs 
